### ISSUE TITLE
MaterialIcons are not being properly implemented within _fonts.scss

### ISSUE THREAD

**Issue by ghost** [monetcap/uikit-react-boilerplate#18]
`_fonts.scss:`

```scss
// _fonts.scss
// Define any typefaces or icon fonts here.

// Base font: Montserrat
// Import from Google fonts with all 3 sizes depicted in wires.
@import url('https://fonts.googleapis.com/css?family=Montserrat:400,500,700');

// Declare local and remote sources for Material Icons.
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(https://example.com/MaterialIcons-Regular.eot); /* For IE6-8 */
  src: local('Material Icons'),
    local('MaterialIcons-Regular'),
    url(https://example.com/MaterialIcons-Regular.woff2) format('woff2'),
    url(https://example.com/MaterialIcons-Regular.woff) format('woff'),
    url(https://example.com/MaterialIcons-Regular.ttf) format('truetype');
}

.uk-button {text-transform: none;}
```

`BrowserConsole Output:`

```
Access to font at 'https://example.com/MaterialIcons-Regular.woff2' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
localhost/:1 GET https://example.com/MaterialIcons-Regular.woff2 net::ERR_FAILED
:8080/#:1 Access to font at 'https://example.com/MaterialIcons-Regular.woff' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
localhost/:1 GET https://example.com/MaterialIcons-Regular.woff net::ERR_FAILED
:8080/#:1 Access to font at 'https://example.com/MaterialIcons-Regular.ttf' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
localhost/:1 GET https://example.com/MaterialIcons-Regular.ttf net::ERR_FAILED
```
